<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>mcp.editor</AssemblyName>
		<PackageId>mcp.editor</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<OutputPath>D:/SteamLibrary/steamapps/common/sbox/.vs/output/</OutputPath>
		<DocumentationFile>D:/SteamLibrary/steamapps/common/sbox/.vs/output/mcp.editor.xml</DocumentationFile>
		<RootNamespace>Sandbox</RootNamespace>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalToolsNamespace" Static="true" />
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.CodeUpgrader.dll"/> 
		<Analyzer Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Generator.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.System.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Engine.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Filesystem.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Reflection.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Mounting.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Microsoft.AspNetCore.Components.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.AppSystem.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Tools.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Compiling.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Microsoft.CodeAnalysis.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Microsoft.CodeAnalysis.CSharp.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Sandbox.Bind.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/Facepunch.ActionGraphs.dll"/> 
		<Reference Include="D:/SteamLibrary/steamapps/common/sbox/bin/managed/SkiaSharp.dll"/> 
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/editor/ActionGraph/Code/actiongraph.csproj" />
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/editor/DooEditor/Code/dooeditor.csproj" />
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/editor/Hammer/Code/hammer.csproj" />
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/addons/tools/Code/Base Editor Library.csproj" />
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/editor/MovieMaker/Code/moviemaker.csproj" />
		<ProjectReference Include="D:/SteamLibrary/steamapps/common/sbox/editor/ShaderGraph/Code/shadergraph.csproj" />
	</ItemGroup>

</Project>
